# Generated by Django 3.2.16 on 2025-03-01 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('logo', models.ImageField(default='default.jpg', upload_to='employer_logo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('qualifications', models.TextField()),
                ('benefits', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time')], max_length=100)),
                ('published_on', models.DateField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vacancy', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Design & Creative', 'Design & Creative'), ('Marketing', 'Marketing'), ('Telemarketing', 'Telemarketing'), ('Software & Web', 'Software & Web'), ('Administration', 'Administration'), ('Teaching & Education', 'Teaching & Education'), ('Engineering', 'Engineering'), ('Garments / Textile', 'Garments / Textile'), ('Others', 'Others')], max_length=100)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to='employer.employer')),
            ],
        ),
    ]
