# Generated by Django 3.2.16 on 2025-03-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='type',
            field=models.CharField(default='Employer', max_length=200),
        ),
    ]
