# Generated by Django 3.2.16 on 2025-03-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_employer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(default='abinraju63@gmail.com', max_length=254),
        ),
    ]
