# Generated by Django 3.2.16 on 2025-03-01 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('type', models.CharField(default='Employee', max_length=200)),
                ('wo_id', models.AutoField(primary_key=True, serialize=False)),
                ('wo_name', models.CharField(max_length=200)),
                ('wo_position', models.CharField(max_length=200)),
                ('wo_email', models.EmailField(max_length=254)),
                ('wo_phone', models.CharField(max_length=200)),
                ('wo_resume', models.FileField(default='default.pdf', upload_to='employee_resume')),
                ('wo_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200)),
                ('wo_dob', models.DateField()),
                ('wo_address', models.TextField()),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wo_applied_jobs', models.ManyToManyField(default=None, related_name='applied_jobs', to='employer.Job')),
            ],
        ),
    ]
