# Generated by Django 3.2.16 on 2025-03-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='wo_phone',
            field=models.CharField(default='1234567890', max_length=200),
        ),
    ]
